export const EXPERIMENT_ALERTS = {
  circuitConnectionsCompleted: {
    description: 'The default wiring path has been placed on the apparatus.',
    target: '#circuit-panel',
    title: 'Circuit Connections Completed Successfully',
    type: 'success',
  },
  connectionsVerified: {
    description: 'You can now set resistance values and power the circuit.',
    target: '#resistance-controls',
    title: 'All Connections Verified Successfully',
    type: 'success',
  },
  connectionErrorFound: {
    target: '#circuit-panel',
    title: 'Connection Error Found - Please Recheck Wiring',
    type: 'error',
  },
  powerOn: {
    description: 'The supply is now feeding the verified circuit.',
    target: '#power-supply',
    title: 'Power Supply Turned ON',
    type: 'success',
  },
  makeConnectionsBeforeMcb: {
    target: '#connection-lab',
    title: 'Make and check the connections before turning on the MCB',
    type: 'warning',
  },
  turnOffMcbBeforeRemovingConnection: {
    target: '#power-toggle-button',
    title: 'Turn off MCB before removing the connection.',
    type: 'warning',
  },
  cannotStartPower: {
    description: 'Run CHECK and correct the circuit wiring before powering the supply.',
    target: '#check-button',
    title: 'Cannot Start Power - Complete Connections First',
    type: 'warning',
  },
  completeConnectionsBeforeAutotransformer: {
    target: '#voltage-control',
    title: 'Please complete the connections first and turn ON the MCB',
    type: 'warning',
  },
  autotransformerReadingsReady: {
    target: '#add-reading-button',
    title: 'The voltage has been set to 230 volts. The readings are now displayed on the voltmeters, ammeter, and wattmeter. Now, click on the Add button to add the readings to the observation table.',
    type: 'info',
  },
  voltageSafetyLimit: {
    dedupeKey: 'step-5-voltage-safety-limit',
    description: 'Reduce the setting if the readings become unstable.',
    duration: 5200,
    target: '#voltage-control',
    title: 'Voltage Approaching Safety Limit',
    type: 'warning',
  },
  rotateAutotransformerBeforeAdd: {
    target: '#voltage-control',
    title: 'Please rotate the autotransformer knob first',
    type: 'warning',
  },
  readingAdded: {
    description: 'The observation row has been stored.',
    target: '#observation-table-panel',
    title: 'Reading Added Successfully',
    type: 'success',
  },
  firstReadingAdded: {
    description: 'Readings added successfully. Turn ON the first switch to connect the first row lamp load. The second reading will then be recorded under load conditions.',
    duration: 7600,
    target: '#lamp-load',
    title: '1st readings added',
    type: 'success',
  },
  secondReadingAdded: {
    description: 'Readings added successfully. Now, turn ON the second switch to increase the load.',
    duration: 6200,
    target: '#lamp-load',
    title: '2nd readings added',
    type: 'success',
  },
  thirdReadingAdded: {
    description: 'Readings added successfully. Now, turn ON the third switch to increase the load.',
    duration: 6200,
    target: '#lamp-load',
    title: '3rd readings added',
    type: 'success',
  },
  fourthReadingAdded: {
    description: 'Readings added successfully. Now, turn ON the last switch to apply the full load.',
    duration: 6200,
    target: '#lamp-load',
    title: '4th readings added',
    type: 'success',
  },
  fifthReadingAdded: {
    description: 'Readings added successfully. Now, click the plot button to generate the graphs',
    duration: 6200,
    target: '#plot-button',
    title: '5th readings added',
    type: 'success',
  },
  readingAlreadyExists: {
    description: 'This reading already exists in the observation table. Turn ON the next enabled switch before adding the readings.',
    duration: 7000,
    target: '#lamp-load',
    title: 'Duplicate Readings',
    type: 'warning',
  },
  firstSwitchOn: {
    description: 'The first row of lamps has been switched ON. The corresponding readings for the first load condition are now displayed. Click the Add button to add the readings to the observation table.',
    duration: 8200,
    target: '#add-reading-button',
    title: 'First Switch ON',
    type: 'info',
  },
  secondSwitchOn: {
    description: 'The second row of lamps has been switched ON. The corresponding readings for an increasing load are now displayed. Click the Add button to add the readings to the observation table.',
    duration: 8200,
    target: '#add-reading-button',
    title: 'Second Switch ON',
    type: 'info',
  },
  thirdSwitchOn: {
    description: 'The third row of lamps has been switched ON. Click the Add button to add the readings to the observation table.',
    duration: 7000,
    target: '#add-reading-button',
    title: 'Third Switch ON',
    type: 'info',
  },
  fourthSwitchOn: {
    description: 'The last row of lamps has been switched ON. Click the Add button to add the readings to the observation table.',
    duration: 7000,
    target: '#add-reading-button',
    title: 'Fourth Switch ON',
    type: 'info',
  },
  minimumReadingsRequired: {
    target: '#observation-table-panel',
    title: 'All 5 Readings Required for Graph Plotting',
    type: 'warning',
  },
  graphPlotted: {
    description: 'The graphs of Efficiency vs Output Power and Voltage Regulation vs Output Power have been plotted successfully. Your simulation is now complete. Click the Generate Report button to view the report. You can then print the simulation or report using the Print button or click Reset to start the simulation again.',
    duration: 12000,
    target: '#results-graphs-panel',
    title: 'Graphs Plotted Successfully',
    type: 'success',
  },
  insufficientGraphReadings: {
    target: '#observation-table-panel',
    title: 'Insufficient Readings to Plot Graph',
    type: 'error',
  },
  reportGenerated: {
    confirmLabel: 'OK',
    description: 'Your report has been generated successfully. Click OK to view your report.',
    placement: 'center',
    requiresConfirmation: true,
    target: '#generate-report-button',
    title: 'Report Generated',
    type: 'success',
  },
  simulationReset: {
    target: '#reset-button',
    title: 'The simulation has been reset. You can start again',
    type: 'info',
  },
}
